function plot_p618_lookup_map_20deg(lutMatFile, target_el)
% PLOT_P618_LOOKUP_MAP_20DEG Plot 20-degree attenuation on a geographic map.
%
% Loads a LUT MAT file generated by generate_p618_lookup_table and plots
% atmospheric attenuation specifically for a 20 degree elevation angle
% overlaid on a geographical map. Supports headless (-nodisplay) execution.
%
% Example:
%   plot_p618_lookup_map_20deg();
%   plot_p618_lookup_map_20deg("p618_lookup_global_1deg_10degel_20260424_090000.mat", 20);

    if nargin < 1 || strlength(string(lutMatFile)) == 0
        files = dir("p618_lookup_*.mat");
        if isempty(files)
            error("No LUT file found. Run generate_p618_lookup_table first.");
        end
        [~, newest_idx] = max([files.datenum]);
        lutMatFile = files(newest_idx).name;
        target_el = 20;
    end
    if nargin < 2
        target_el = 20;
    end

    fprintf("Loading LUT: %s\n", lutMatFile);
    S = load(lutMatFile, "LUT");
    LUT = S.LUT;

    % 1. Extract specifically the 20-degree elevation slice
    el_idx = find(LUT.el_deg == target_el, 1);
    
    if isempty(el_idx)
        % Fallback if exactly 20 is missing
        [~, el_idx] = min(abs(LUT.el_deg - target_el));
        fprintf("Exact 20 deg not found. Using nearest available: %d deg\n", LUT.el_deg(el_idx));
    end
    
    % LUT.At_dB is dimensioned (lat, lon, el)
    at_20deg_dB = double(LUT.At_dB(:, :, el_idx)); 

    [lon_mesh, lat_mesh] = meshgrid(round(LUT.lon_deg), round(LUT.lat_deg));

    lat_lim = [ceil(min(LUT.lat_deg)), floor(max(LUT.lat_deg))];
    lon_lim = [ceil(min(LUT.lon_deg)), floor(max(LUT.lon_deg))];

    is_global = isequal(lat_lim, [-90, 90]) && isequal(lon_lim, [-180, 180]);

    % 2. Initialize figure for headless (-nodisplay) execution
    f = figure('Visible', 'off', 'Color', 'w', 'Position', [100, 100, 1400, 800]);

    % 3. Set up the map projection dynamically
    if is_global
        % Robinson is standard for global maps. Origin centers it on the prime meridian.
        axesm('robinson', 'MapLatLimit', lat_lim, 'MapLonLimit', lon_lim, ...
              'Origin', [0, 0, 0], ...
              'Frame', 'on', 'Grid', 'on', 'MeridianLabel', 'on', 'ParallelLabel', 'on');
    else
        % Calculate the exact center longitude of your region
        center_lon = mean(lon_lim);
        
        % Lambert standard is better for regional boxes.
        % The 'Origin' vector [0, center_lon, 0] rotates the globe so your region faces forward.
        axesm('lambertstd', 'MapLatLimit', lat_lim, 'MapLonLimit', lon_lim, ...
              'Origin', [0, center_lon, 0], ...
              'Frame', 'on', 'Grid', 'on', 'MeridianLabel', 'on', 'ParallelLabel', 'on');
    end
    axis off;
    
    % 4. Load standard MATLAB land boundaries and draw them
    try
        land = shaperead('landareas.shp', 'UseGeoCoords', true);
        geoshow([land.Lat], [land.Lon], 'DisplayType', 'polygon', 'FaceColor', [0.85 0.85 0.85]);
    catch
        warning("Mapping Toolbox shaperead failed. Land outlines will not be drawn.");
    end

    % 5. Overlay the attenuation data
    % FaceAlpha adds transparency so landmasses remain visible underneath
    surfm(lat_mesh, lon_mesh, at_20deg_dB, 'FaceAlpha', 0.65, 'EdgeColor', 'none');

    % 6. Aesthetics and labeling
    colormap(turbo);
    cb = colorbar;
    cb.Label.String = "Attenuation At (dB)";
    cb.Label.FontSize = 12;
    cb.Label.FontWeight = 'bold';
    
    set(gca, 'FontSize', 12);
    
    title_str = sprintf("Atmospheric Attenuation |el=%d deg| | f=%.1f GHz | p=%.2f%%", ...
        LUT.el_deg(el_idx), LUT.frequency_hz / 1e9, LUT.total_annual_exceedance_pct);
    title(title_str, 'FontSize', 16);

    % 7. Save output to file and close
    out_name = sprintf("screenshots/Map_P618_el%ddeg_f%.1fGHz_%s.png", ...
        LUT.el_deg(el_idx), LUT.frequency_hz / 1e9, datestr(now, "yyyymmdd_HHMMSS"));
        
    fprintf("Rendering map and saving to %s...\n", out_name);
    exportgraphics(f, out_name, 'Resolution', 300);
    close(f);
    
    fprintf("Done.\n");
end